name: Docker Image CI

on:
  workflow_dispatch:
    inputs:
      image_purpose:
        description: 'Purpose of the image'
        required: true
        type: choice
        options:
          - testing
          - production
      caddy_version:
        description: 'Version of Caddy to build from'
        required: true
        default: '2.8.4'
      extra_tag:
        description: 'Tag to append to the verison number'
        required: true
        default: ''
          
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run date command
      id: date
      run: |
        buildTime=$(date +%Y-%m-%d" "%X)
        echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT

    - name: Get release tag
      id: release
      run: |
        if [ "${{ github.event.inputs.image_purpose }}" == "testing" ]; then
          buildTag=$(date +%Y-%m-%d-%H-%M)
          echo "GH_BUILD_TAG=$buildTag" >> $GITHUB_OUTPUT
          echo "GH_LATEST_TAG=testing" >> $GITHUB_OUTPUT
        elif [ "${{ github.event.inputs.image_purpose }}" == "production" ]; then
          echo "GH_BUILD_TAG=${{ github.event.inputs.caddy_version }}-alpine-${{ github.event.inputs.extra_tag }}" >> $GITHUB_OUTPUT
          echo "GH_LATEST_TAG=latest" >> $GITHUB_OUTPUT
        else
          echo "Invalid base image specified" >&2
          exit 1
        fi

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        # platforms: linux/arm64
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/caddy:${{ steps.release.outputs.GH_BUILD_TAG }}
          ${{ secrets.DOCKERHUB_USERNAME }}/caddy:${{ steps.tag.outputs.GH_LATEST_TAG }}
        build-args: |
          BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
          CADDY_VERSION=${{ github.event.inputs.caddy_version }}
