name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Run date command
      id: date
      run: |
        buildTime=$(date +%Y-%m-%d" "%X)
        echo "BUILD_TIME=$buildTime" >> $GITHUB_OUTPUT
        # echo "::set-output name=output::$DATE"

    - name: Get release tag
      id: release
      run: |
        caddyVersion="2.7.6"
        echo "CADDY_VERSION=$caddyVersion " >> $GITHUB_OUTPUT

    - name: Login to DockerHub
      uses: docker/login-action@v3 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build and push
      id: docker_build
      uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        platforms: linux/amd64,linux/arm64,linux/arm/v7,linux/arm/v6
        tags: |
          ${{ secrets.DOCKERHUB_USERNAME }}/caddy_webproc:${{ steps.release.outputs.CADDY_VERSION }}-alpine
          ${{ secrets.DOCKERHUB_USERNAME }}/caddy_webproc:latest
        build-args: |
          CADDY_VERSION=${{ steps.release.outputs.CADDY_VERSION }}
          BUILD_TIME=${{ steps.date.outputs.BUILD_TIME }}
